# Generated by Django 3.0 on 2022-10-24 15:01

from django.db import migrations


def transfer_model_records(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    ProfileOld = apps.get_model('oc_lettings_site', 'Profile')
    Profilenew = apps.get_model('profiles', 'Profile')

    for profile_old in ProfileOld.objects.using(db_alias).all():
        instance_dict = profile_old.__dict__
        instance_dict.pop('_state')
        Profilenew.objects.using(db_alias).create(**instance_dict)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0001_initial')
    ]

    operations = [
        migrations.RunPython(transfer_model_records, migrations.RunPython.noop)
    ]
