version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: lint
          command: flake8
      - run:
          name: run tests
          command: python manage.py test

  build-and-push-to-dockerhub:
    machine: true
    steps:
      - checkout
      - run: |
          echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run: docker build -t $DOCKERHUB_USERNAME/oc-lettings:$CIRCLE_SHA1 .
      - run: docker push $DOCKERHUB_USERNAME/oc-lettings:$CIRCLE_SHA1

workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint
      - build-and-push-to-dockerhub:
          filters:
            branches:
              only:
                - master
          requires:
            - test-and-lint
